---
- name: stop auditd
  command: "service auditd stop"
  changed_when: false
  environment:
    PATH: '/usr/sbin:/usr/bin:/sbin:/bin'
  args:
    warn: false

- name: disable auditd service
  service:
    name: auditd
    state: stopped
    enabled: false

- name: disable audit in grub config
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]audit=).)*)(?:[" ]audit=\S+)?(.*")$'
    replace: '\1\2'
