---
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-starting_the_audit_service
- name: restart auditd
  command: "service auditd restart"
  environment:
    PATH: '/usr/sbin:/usr/bin:/sbin:/bin'
  args:
    warn: false
